links:
- product: chrome
  url: crbug.com/711704
  results:
  - test: floats-rule3-outside-left-002.xht
  - test: floats-rule3-outside-right-002.xht
  - test: floats-rule7-outside-left-001.xht
  - test: floats-rule7-outside-right-001.xht
  - test: floats-wrap-bfc-006.xht
