links:
- product: chrome
  url: crbug.com/1129522
  results:
  - test: shape-outside-border-box-border-radius-008.html
  - test: shape-outside-border-box-border-radius-011.html
  - test: shape-outside-border-box-border-radius-010.html
  - test: shape-outside-border-box-border-radius-012.html
  - test: shape-outside-border-box-border-radius-009.html
  - test: shape-outside-border-box-border-radius-006.html
  - test: shape-outside-border-box-border-radius-007.html
  - test: shape-outside-border-box-border-radius-005.html
