links:
- product: chrome
  url: crbug.com/1129522
  results:
  - test: shape-outside-inset-023.html
  - test: shape-outside-inset-027.html
  - test: shape-outside-inset-022.html
  - test: shape-outside-inset-026.html
