links:
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1687918
      results:
        - test: historical.html
          subtest: TouchEvent::initTouchEvent
    - product: chrome
      url: https://crbug.com/1155621
      results:
        - test: touch-globaleventhandler-interface.html
