links:
    - product: chrome
      url: https://crbug.com/1082020
      results:
        - test: link-web-bundle.tentative.html
        - test: subresource-loading-from-web-bundle.tentative.html
        - test: subresource-loading-nested-bundle.tentative.html
        - test: subresource-loading-path-restriction.tentative.html
