links:
- product: chrome
  url: crbug.com/711805
  results:
  - test: abspos-inline-001.xht
  - test: abspos-inline-002.xht
  - test: abspos-inline-003.xht
  - test: abspos-inline-004.xht
  - test: abspos-inline-005.xht
  - test: abspos-inline-006.xht
  - test: abspos-paged-001.xht
  - test: abspos-paged-002.xht
  - test: position-004.xht
  - test: position-fixed-003.xht
  - test: position-fixed-004.xht
  - test: position-fixed-005.xht
  - test: position-relative-020.xht
  - test: position-relative-021.xht
  - test: position-relative-022.xht
  - test: position-relative-034.xht
  - test: position-relative-035.xht
  - test: position-relative-036.xht
