links:
- product: chrome
  url: crbug.com/954898
  results:
  - test: overflowing-snap-areas.html
    status: FAIL
- product: chrome
  url: crbug.com/984438
  results:
  - test: snap-at-user-scroll-end-manual.html
- product: chrome
  url: crbug.com/1003055
  results:
  - test: scroll-target-align-001.html
  - test: scroll-target-align-002.html
  - test: scroll-target-snap-001.html
  - test: scroll-target-snap-002.html
