links:
    - product: chrome
      url: https://crbug.com/954898
      results:
        - test: overflowing-snap-areas.html
          status: FAIL
    - product: chrome
      url: https://crbug.com/956576
      results:
        - test: snap-inline-block.html
