links:
- product: firefox
  results:
  - subtest: .flexbox 24
    test: position-absolute-001.html
  - subtest: .flexbox 29
    test: position-absolute-001.html
  - subtest: .flexbox 34
    test: position-absolute-001.html
  - subtest: .flexbox 39
    test: position-absolute-001.html
  - subtest: .flexbox 64
    test: position-absolute-001.html
  - subtest: .flexbox 69
    test: position-absolute-001.html
  - subtest: .flexbox 74
    test: position-absolute-001.html
  - subtest: .flexbox 79
    test: position-absolute-001.html
  - subtest: .flexbox 104
    test: position-absolute-001.html
  - subtest: .flexbox 109
    test: position-absolute-001.html
  - subtest: .flexbox 114
    test: position-absolute-001.html
  - subtest: .flexbox 119
    test: position-absolute-001.html
  - subtest: .flexbox 5
    test: position-absolute-002.html
  - subtest: .flexbox 99
    test: position-absolute-013.html
  - subtest: .flexbox 102
    test: position-absolute-013.html
  - subtest: .flexbox 105
    test: position-absolute-013.html
  - subtest: .flexbox 108
    test: position-absolute-013.html
  - subtest: .flexbox 111
    test: position-absolute-013.html
  - subtest: .flexbox 114
    test: position-absolute-013.html
  - subtest: .flexbox 117
    test: position-absolute-013.html
  - subtest: .flexbox 120
    test: position-absolute-013.html
  - subtest: .flexbox 123
    test: position-absolute-013.html
  - subtest: .flexbox 126
    test: position-absolute-013.html
  - subtest: .flexbox 129
    test: position-absolute-013.html
  - subtest: .flexbox 132
    test: position-absolute-013.html
  - subtest: .flexbox 135
    test: position-absolute-013.html
  - subtest: .flexbox 138
    test: position-absolute-013.html
  - subtest: .flexbox 141
    test: position-absolute-013.html
  - subtest: .flexbox 144
    test: position-absolute-013.html
  - subtest: .flexbox 243
    test: position-absolute-013.html
  - subtest: .flexbox 246
    test: position-absolute-013.html
  - subtest: .flexbox 249
    test: position-absolute-013.html
  - subtest: .flexbox 252
    test: position-absolute-013.html
  - subtest: .flexbox 255
    test: position-absolute-013.html
  - subtest: .flexbox 258
    test: position-absolute-013.html
  - subtest: .flexbox 261
    test: position-absolute-013.html
  - subtest: .flexbox 264
    test: position-absolute-013.html
  - subtest: .flexbox 267
    test: position-absolute-013.html
  - subtest: .flexbox 270
    test: position-absolute-013.html
  - subtest: .flexbox 273
    test: position-absolute-013.html
  - subtest: .flexbox 276
    test: position-absolute-013.html
  - subtest: .flexbox 279
    test: position-absolute-013.html
  - subtest: .flexbox 282
    test: position-absolute-013.html
  - subtest: .flexbox 285
    test: position-absolute-013.html
  - subtest: .flexbox 288
    test: position-absolute-013.html
  - subtest: .flexbox 387
    test: position-absolute-013.html
  - subtest: .flexbox 390
    test: position-absolute-013.html
  - subtest: .flexbox 393
    test: position-absolute-013.html
  - subtest: .flexbox 396
    test: position-absolute-013.html
  - subtest: .flexbox 399
    test: position-absolute-013.html
  - subtest: .flexbox 402
    test: position-absolute-013.html
  - subtest: .flexbox 405
    test: position-absolute-013.html
  - subtest: .flexbox 408
    test: position-absolute-013.html
  - subtest: .flexbox 411
    test: position-absolute-013.html
  - subtest: .flexbox 414
    test: position-absolute-013.html
  - subtest: .flexbox 417
    test: position-absolute-013.html
  - subtest: .flexbox 420
    test: position-absolute-013.html
  - subtest: .flexbox 423
    test: position-absolute-013.html
  - subtest: .flexbox 426
    test: position-absolute-013.html
  - subtest: .flexbox 429
    test: position-absolute-013.html
  - subtest: .flexbox 432
    test: position-absolute-013.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1686823
