links:
    - product: chrome
      url: https://crbug.com/924472
      results:
        - test: transform-box-valid.html
          status: FAIL
        - test: transform-box-computed.html
          status: FAIL
    - product: chrome
      url: https://crbug.com/979895
      results:
        - test: translate-parsing-valid.html
