links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=190217
  results:
  - test: '*'
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=190217
  results:
  - test: '*'
- product: chrome
  url: crbug.com/1029941
  results:
  - test: background-image-alpha.https.html
