links:
    - product: webkitgtk
      url: https://bugs.webkit.org/show_bug.cgi?id=206409
      results:
        - test: overflow-padding.html
          status: FAIL
    - product: chrome
      url: https://crbug.com/1007065
      results:
        - test: overflow-codependent-scrollbars.html
          status: FAIL
    - product: chrome
      url: https://crbug.com/966283
      results:
        - test: overflow-body-propagation-007.html
        - test: overflow-body-propagation-008.html
        - test: overflow-body-propagation-009.html
    - product: chrome
      url: https://crbug.com/993813
      results:
        - test: webkit-line-clamp-008.html
        - test: webkit-line-clamp-029.html
        - test: webkit-line-clamp-025.html
    - product: chrome
      url: https://crbug.com/305376
      results:
        - test: webkit-line-clamp-018.html
        - test: webkit-line-clamp-024.html
    - product: chrome
      url: https://crbug.com/745905
      results:
        - test: text-overflow-scroll-vertical-lr-001.html
        - test: text-overflow-scroll-vertical-lr-rtl-001.html
        - test: text-overflow-scroll-vertical-rl-001.html
        - test: text-overflow-scroll-vertical-rl-rtl-001.html
        - test: text-overflow-scroll-001.html
        - test: text-overflow-scroll-rtl-001.html
    - product: chrome
      url: https://crbug.com/1067031
      results:
        - test: webkit-line-clamp-035.html
        - test: text-overflow-ellipsis-002.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1672652
      results:
        - test: overflow-clip-margin-002.html
    - product: firefox
      url: https://bugzilla.mozilla.org/show_bug.cgi?id=1685743
      results:
        - test: overflow-clip-margin-005.html
    - product: chrome
      url: https://crbug.com/1087667
      results:
        - test: clip-003.html
        - test: overflow-clip-cant-scroll.html
        - test: overflow-clip-content-visual-overflow.html
        - test: overflow-clip-margin-001.html
        - test: overflow-clip-margin-002.html
        - test: overflow-clip-margin-invalidation.html
    - product: chrome
      url: https://crbug.com/1046544
      results:
        - test: incremental-scroll.html
