links:
- product: firefox
  results:
  - subtest: no separator - move up
    test: caret-navigation-around-line-break.html
  - subtest: <br> separator - move down
    test: caret-navigation-around-line-break.html
  - subtest: <br> separator - move up
    test: caret-navigation-around-line-break.html
  - subtest: <wbr> separator - move right
    test: caret-navigation-around-line-break.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1669344
