links:
    - product: chrome
      url: https://crbug.com/1133310
      results:
        - test: trust-token-parameter-validation.tentative.https.html
        - test: trust-token-parameter-validation-xhr.tentative.https.html
