links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=169271
  results:
  - test: grid-items-sizing-alignment-001.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191365
  results:
  - test: item-with-table-with-infinite-max-intrinsic-width.html
    status: FAIL
  - test: table-with-infinite-max-intrinsic-width.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191460
  results:
  - test: anonymous-grid-item-001.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191461
  results:
  - test: percentage-size-subitems-001.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191462
  results:
  - test: percentage-size-replaced-subitems-001.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=191463
  results:
  - test: explicitly-sized-grid-item-as-table.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=169271
  results:
  - test: grid-items-sizing-alignment-001.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=191365
  results:
  - test: item-with-table-with-infinite-max-intrinsic-width.html
    status: FAIL
  - test: table-with-infinite-max-intrinsic-width.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=191460
  results:
  - test: anonymous-grid-item-001.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=191463
  results:
  - test: explicitly-sized-grid-item-as-table.html
    status: FAIL
- product: webkitgtk
  url: fdgfd
  results:
  - test: grid-item-percentage-sizes-002.html
