links:
- product: chrome
  url: crbug.com/1129522
  results:
  - test: shape-outside-circle-043.html
  - test: shape-outside-circle-052.html
  - test: shape-outside-circle-053.html
  - test: shape-outside-circle-037.html
