links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203530
  results:
  - test: text-decoration-line-recalc.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203531
  results:
  - test: text-decoration-propagation-shadow.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203528
  results:
  - test: text-decoration-thickness-linethrough-001.html
    status: FAIL
  - test: text-decoration-thickness-overline-001.html
    status: FAIL
  - test: text-decoration-thickness-scroll-001.html
    status: FAIL
  - test: text-decoration-thickness-underline-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-002.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=203529
  results:
  - test: text-decoration-underline-position-vertical-ja.html
    status: FAIL
  - test: text-decoration-underline-position-vertical.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203530
  results:
  - test: text-decoration-line-recalc.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203531
  results:
  - test: text-decoration-propagation-shadow.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203528
  results:
  - test: text-decoration-thickness-linethrough-001.html
    status: FAIL
  - test: text-decoration-thickness-overline-001.html
    status: FAIL
  - test: text-decoration-thickness-scroll-001.html
    status: FAIL
  - test: text-decoration-thickness-underline-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-001.html
    status: FAIL
  - test: text-decoration-thickness-vertical-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=203529
  results:
  - test: text-decoration-underline-position-vertical-ja.html
    status: FAIL
  - test: text-decoration-underline-position-vertical.html
    status: FAIL
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1643421
  results:
  - test: text-decoration-thickness-from-font-variable.html
- product: chrome
  url: crbug.com/785230
  results:
  - test: text-decoration-shorthands-001.html
    status: FAIL
  - test: text-decoration-shorthands-002.html
    status: FAIL
  - test: text-decoration-thickness-valid.html
    status: FAIL
  - test: text-decoration-thickness-ink-skip-dilation.html
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1667198
  results:
  - test: text-decoration-color.html
- product: chrome
  url: crbug.com/1008951
  results:
  - test: text-decoration-subelements-002.html
  - test: text-decoration-subelements-003.html
  - test: text-decoration-color.html
- product: chrome
  url: crbug.com/666433
  results:
  - test: text-emphasis-color-001.xht
  - test: text-emphasis-position-above-left-001.xht
  - test: text-emphasis-position-above-left-002.xht
  - test: text-emphasis-position-above-right-001.xht
  - test: text-emphasis-position-above-right-002.xht
  - test: text-emphasis-position-below-left-001.xht
  - test: text-emphasis-position-below-left-002.xht
  - test: text-emphasis-position-below-right-001.xht
  - test: text-emphasis-position-below-right-002.xht
  - test: text-emphasis-style-002.html
  - test: text-emphasis-style-006.html
  - test: text-emphasis-style-007.html
  - test: text-emphasis-style-008.html
  - test: text-emphasis-style-010.html
  - test: text-emphasis-style-012.html
  - test: text-emphasis-style-021.html
  - test: text-emphasis-style-filled-001.xht
  - test: text-emphasis-style-open-001.xht
  - test: text-emphasis-style-shape-001.xht
  - test: text-emphasis-style-string-001.xht
- product: chrome
  url: crbug.com/949909
  results:
  - test: text-underline-position-073-manual.html
  - test: text-underline-position-072-manual.html
  - test: text-underline-position-071-manual.html
  - test: text-underline-position-020-manual.html
  - test: text-underline-position-076-manual.html
  - test: text-underline-position-075-manual.html
  - test: text-underline-position-021-manual.html
  - test: text-underline-position-022-manual.html
  - test: text-underline-position-074-manual.html
  - test: text-underline-position-019-manual.html
  - test: text-decoration-line-048-manual.html
  - test: text-decoration-line-046a-manual.html
  - test: text-decoration-line-082-manual.html
  - test: text-decoration-line-048a-manual.html
  - test: text-decoration-line-085-manual.html
  - test: text-decoration-line-044-manual.html
  - test: text-decoration-line-097a-manual.html
  - test: text-decoration-line-001-manual.html
  - test: text-decoration-line-090-manual.html
  - test: text-decoration-line-092-manual.html
  - test: text-decoration-line-095-manual.html
  - test: text-decoration-line-095a-manual.html
  - test: text-decoration-line-040a-manual.html
  - test: text-decoration-line-096a-manual.html
  - test: text-decoration-line-002-manual.html
  - test: text-decoration-line-045-manual.html
  - test: text-decoration-line-091-manual.html
  - test: text-decoration-line-092a-manual.html
  - test: text-decoration-line-004-manual.html
  - test: text-decoration-line-096-manual.html
  - test: text-decoration-line-040-manual.html
  - test: text-decoration-line-003-manual.html
  - test: text-decoration-line-091a-manual.html
  - test: text-decoration-line-097-manual.html
  - test: text-decoration-line-041-manual.html
  - test: text-decoration-line-049-manual.html
  - test: text-decoration-line-090a-manual.html
  - test: text-decoration-090a-manual.html
  - test: text-decoration-046a-manual.html
  - test: text-decoration-091-manual.html
  - test: text-decoration-048a-manual.html
  - test: text-decoration-092a-manual.html
  - test: text-decoration-096-manual.html
  - test: text-decoration-048-manual.html
  - test: text-decoration-003-manual.html
  - test: text-decoration-091a-manual.html
  - test: text-decoration-002-manual.html
  - test: text-decoration-090-manual.html
  - test: text-decoration-092-manual.html
  - test: text-decoration-095a-manual.html
  - test: text-decoration-049-manual.html
  - test: text-decoration-041-manual.html
  - test: text-decoration-040a-manual.html
  - test: text-decoration-097-manual.html
  - test: text-decoration-001-manual.html
  - test: text-decoration-045-manual.html
  - test: text-decoration-082-manual.html
  - test: text-decoration-096a-manual.html
  - test: text-decoration-044-manual.html
  - test: text-decoration-004-manual.html
  - test: text-decoration-085-manual.html
  - test: text-decoration-097a-manual.html
  - test: text-decoration-040-manual.html
- product: chrome
  url: crbug.com/1054656
  results:
  - test: text-decoration-skip-ink-005.html
- product: chrome
  url: crbug.com/1133806
  results:
  - test: text-decoration-thickness-vertical-002.html
  - test: text-underline-offset-vertical-002.html
  - test: text-decoration-skip-ink-upright-002.html
  - test: text-decoration-skip-ink-upright-001.html
