links:
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1642534
  results:
  - test: min-height-applies-to-013.xht
  - test: min-height-applies-to-014.xht
- product: chrome
  url: crbug.com/711807
  results:
  - test: block-in-inline-insert-001f.xht
  - test: block-in-inline-insert-002f.xht
  - test: inline-block-002.xht
  - test: inline-block-003.xht
  - test: inline-block-004.xht
  - test: inline-block-005.xht
  - test: inlines-003.xht
  - test: inlines-004.xht
  - test: inlines-005.xht
  - test: inlines-006.xht
  - test: max-width-applies-to-005.xht
  - test: max-width-applies-to-006.xht
  - test: max-width-applies-to-013.xht
  - test: max-width-applies-to-014.xht
  - test: min-width-applies-to-005.xht
  - test: min-width-applies-to-006.xht
  - test: min-width-applies-to-014.xht
  - test: replaced-intrinsic-001.xht
  - test: replaced-intrinsic-002.xht
