links:
- product: chrome
  url: crbug.com/791529
  results:
  - test: variable-transitions-from-no-value.html
  - test: variable-transitions-to-no-value.html
  - test: variable-transitions-transition-property-variable-before-value.html
  - test: variable-transitions-value-before-transition-property-variable.html
