links:
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=197970
  results:
  - test: break-spaces-010.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=183258
  results:
  - test: textarea-pre-wrap-012.html
    status: FAIL
  - test: textarea-pre-wrap-013.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=195275
  results:
  - test: line-edge-white-space-collapse-001.html
    status: FAIL
  - test: line-edge-white-space-collapse-002.html
    status: FAIL
  - test: pre-wrap-014.html
    status: FAIL
  - test: tab-stop-threshold-002.html
    status: FAIL
  - test: tab-stop-threshold-004.html
    status: FAIL
  - test: tab-stop-threshold-006.html
    status: FAIL
  - test: text-space-collapse-discard-001.xht
    status: FAIL
  - test: text-space-collapse-preserve-breaks-001.xht
    status: FAIL
  - test: text-space-trim-trim-inner-001.xht
    status: FAIL
  - test: trailing-ideographic-space-001.html
    status: FAIL
  - test: trailing-ideographic-space-002.html
    status: FAIL
  - test: trailing-ideographic-space-003.html
    status: FAIL
  - test: trailing-ideographic-space-004.html
    status: FAIL
  - test: white-space-intrinsic-size-001.html
    status: FAIL
  - test: white-space-pre-wrap-trailing-spaces-002.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=195345
  results:
  - test: break-spaces-before-first-char-003.html
    status: FAIL
  - test: break-spaces-before-first-char-006.html
    status: FAIL
  - test: break-spaces-before-first-char-013.html
    status: FAIL
- product: safari
  url: https://bugs.webkit.org/show_bug.cgi?id=197277
  results:
  - test: break-spaces-008.html
    status: FAIL
  - test: break-spaces-before-first-char-004.html
    status: FAIL
  - test: break-spaces-before-first-char-005.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=183258
  results:
  - test: textarea-pre-wrap-012.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=195275
  results:
  - test: line-edge-white-space-collapse-001.html
    status: FAIL
  - test: line-edge-white-space-collapse-002.html
    status: FAIL
  - test: pre-wrap-014.html
    status: FAIL
  - test: tab-stop-threshold-002.html
    status: FAIL
  - test: tab-stop-threshold-004.html
    status: FAIL
  - test: tab-stop-threshold-006.html
    status: FAIL
  - test: text-space-collapse-discard-001.xht
    status: FAIL
  - test: text-space-collapse-preserve-breaks-001.xht
    status: FAIL
  - test: text-space-trim-trim-inner-001.xht
    status: FAIL
  - test: trailing-ideographic-space-001.html
    status: FAIL
  - test: trailing-ideographic-space-002.html
    status: FAIL
  - test: trailing-ideographic-space-003.html
    status: FAIL
  - test: trailing-ideographic-space-004.html
    status: FAIL
  - test: white-space-intrinsic-size-001.html
    status: FAIL
  - test: white-space-pre-wrap-trailing-spaces-002.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=195345
  results:
  - test: break-spaces-before-first-char-006.html
    status: FAIL
  - test: break-spaces-before-first-char-013.html
    status: FAIL
- product: webkitgtk
  url: https://bugs.webkit.org/show_bug.cgi?id=197277
  results:
  - test: break-spaces-008.html
    status: FAIL
  - test: break-spaces-before-first-char-004.html
    status: FAIL
  - test: break-spaces-before-first-char-005.html
    status: FAIL
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1634314
  results:
  - test: white-space-intrinsic-size-013.html
  - test: white-space-intrinsic-size-014.html
- product: chrome
  url: crbug.com/991413
  results:
  - test: break-spaces-006.html
    status: FAIL
  - test: trailing-other-space-separators-001.html
  - test: trailing-other-space-separators-002.html
  - test: trailing-other-space-separators-003.html
  - test: trailing-other-space-separators-004.html
  - test: trailing-other-space-separators-break-spaces-001.html
  - test: trailing-other-space-separators-break-spaces-002.html
  - test: trailing-other-space-separators-break-spaces-003.html
  - test: trailing-other-space-separators-break-spaces-004.html
  - test: trailing-other-space-separators-break-spaces-005.html
  - test: trailing-other-space-separators-break-spaces-006.html
  - test: trailing-other-space-separators-break-spaces-007.html
  - test: trailing-other-space-separators-break-spaces-008.html
  - test: trailing-other-space-separators-break-spaces-010.html
  - test: trailing-other-space-separators-break-spaces-011.html
  - test: trailing-other-space-separators-break-spaces-012.html
  - test: trailing-other-space-separators-break-spaces-014.html
  - test: trailing-other-space-separators-break-spaces-015.html
- product: chrome
  url: crbug.com/918764
  results:
  - test: tab-stop-threshold-005.html
    status: FAIL
- product: firefox
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1665027
  results:
  - test: white-space-pre-wrap-trailing-spaces-012.html
  - test: white-space-pre-wrap-trailing-spaces-014.html
- product: chrome
  url: crbug.com/972992
  results:
  - test: white-space-pre-wrap-trailing-spaces-003.html
- product: chrome
  url: crbug.com/1008029
  results:
  - test: pre-wrap-019.html
  - test: textarea-pre-wrap-012.html
  - test: textarea-pre-wrap-013.html
- product: chrome
  url: crbug.com/1071928
  results:
  - test: white-space-intrinsic-size-013.html
  - test: white-space-intrinsic-size-014.html
- product: chrome
  url: crbug.com/893490
  results:
  - test: control-chars-00D.html
  - test: control-chars-07F.html
  - test: control-chars-080.html
  - test: control-chars-081.html
  - test: control-chars-082.html
  - test: control-chars-083.html
  - test: control-chars-084.html
  - test: control-chars-085.html
  - test: control-chars-086.html
  - test: control-chars-087.html
  - test: control-chars-088.html
  - test: control-chars-089.html
  - test: control-chars-08A.html
  - test: control-chars-08B.html
  - test: control-chars-08C.html
  - test: control-chars-08D.html
  - test: control-chars-08E.html
  - test: control-chars-08F.html
  - test: control-chars-090.html
  - test: control-chars-091.html
  - test: control-chars-092.html
  - test: control-chars-093.html
  - test: control-chars-094.html
  - test: control-chars-095.html
  - test: control-chars-096.html
  - test: control-chars-097.html
  - test: control-chars-098.html
  - test: control-chars-099.html
  - test: control-chars-09A.html
  - test: control-chars-09B.html
  - test: control-chars-09C.html
  - test: control-chars-09D.html
  - test: control-chars-09E.html
  - test: control-chars-09F.html
- product: chrome
  url: crbug.com/1015331
  results:
  - test: eol-spaces-bidi-001.html
